# Generated by Django 2.1.2 on 2018-10-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='DayOff',
        ),
    ]
