# Generated by Django 2.1.2 on 2018-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifty', '0002_auto_20181025_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='end',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='start',
            field=models.DateField(max_length=20),
        ),
    ]
