# Generated by Django 2.1.2 on 2018-11-05 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifty', '0003_auto_20181025_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='name',
        ),
        migrations.AddField(
            model_name='dayoff',
            name='all_day',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayoff',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='start',
            field=models.DateField(),
        ),
    ]
