# Generated by Django 2.1.2 on 2018-11-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifty', '0005_auto_20181105_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
