# Generated by Django 2.1.2 on 2018-11-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifty', '0006_dayoff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='name',
        ),
    ]
