# Generated by Django 2.1.2 on 2018-11-05 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifty', '0007_remove_dayoff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
