# Generated by Django 2.1.2 on 2018-11-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifty', '0008_auto_20181105_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
